Repository bar-d/ios-open-market, pull requests merged in 2022-08, with the labels that each got.

#25 Refactor 7 step3review
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket.xcodeproj/xcshareddata/xcschemes/OpenMarket.xcscheme
  OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
  OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
  OpenMarket/OpenMarket/Controller/ProductUpdateViewController.swift
  OpenMarket/OpenMarket/Model/Data/ImageCacheManager.swift
  OpenMarket/OpenMarket/Model/Data/OpenMarketRepository.swift
  OpenMarket/OpenMarket/Model/Data/OpenMarketRequest.swift
  OpenMarket/OpenMarket/Model/Enum/NameSpace.swift
  OpenMarket/OpenMarket/Model/Extension/Data+extension.swift
  OpenMarket/OpenMarket/Model/Extension/UIView+extension.swift
  OpenMarket/OpenMarket/Model/JSONModel/ProductDetail.swift
  OpenMarket/OpenMarket/Model/Network/APIRequest.swift
  OpenMarket/OpenMarket/Model/Protocol/Requestable.swift
  OpenMarket/OpenMarket/View/GridCollecntionView.swift
  OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
  OpenMarket/OpenMarket/View/ListCollectionView.swift
  OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
  OpenMarket/OpenMarket/View/ProductRegistrationView.swift
  OpenMarket/OpenMarket/View/ProductUpdateView.swift
Labels: style, refactor

#26 Refactor 7 step3review
  OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
  OpenMarket/OpenMarket/Model/Data/OpenMarketRequest.swift
  OpenMarket/OpenMarket/Model/Network/APIRequest.swift
  OpenMarket/OpenMarket/View/ProductRegistrationView.swift
  README.md
Labels: refactor, docs

#27 Refactor 7 step3review
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/DataManager/ImageCacheManager.swift
  OpenMarket/OpenMarket/DataManager/OpenMarketImageManager.swift
  OpenMarket/OpenMarket/Enum/Currency.swift
  OpenMarket/OpenMarket/Error/CodableError.swift
  OpenMarket/OpenMarket/Error/DataError.swift
  OpenMarket/OpenMarket/Error/NetworkError.swift
  OpenMarket/OpenMarket/Extension/Data+extension.swift
  OpenMarket/OpenMarket/Extension/Double+extension.swift
  OpenMarket/OpenMarket/Extension/UIImage+extension.swift
  OpenMarket/OpenMarket/Extension/UIView+extension.swift
  OpenMarket/OpenMarket/JSONModel/ProductDetail.swift
  OpenMarket/OpenMarket/JSONModel/ProductImage.swift
  OpenMarket/OpenMarket/JSONModel/ProductsDetailList.swift
  OpenMarket/OpenMarket/JSONModel/ProductsList.swift
  OpenMarket/OpenMarket/JSONModel/RegisterationProduct.swift
  OpenMarket/OpenMarket/JSONModel/SecretProducts.swift
  OpenMarket/OpenMarket/Model/Data/OpenMarketRequest.swift
  OpenMarket/OpenMarket/Model/Network/APIRequest.swift
  OpenMarket/OpenMarket/Network/APIRequest.swift
  OpenMarket/OpenMarket/Network/MyURLSession.swift
  OpenMarket/OpenMarket/Network/SessionProtocol.swift
  OpenMarket/OpenMarket/OpenMarketRequest/ImageGetRequest.swift
  OpenMarket/OpenMarket/OpenMarketRequest/ProductDeleteRequest.swift
  OpenMarket/OpenMarket/OpenMarketRequest/ProductGetRequest.swift
  OpenMarket/OpenMarket/OpenMarketRequest/ProductPatchRequest.swift
  OpenMarket/OpenMarket/OpenMarketRequest/ProductPostRequest.swift
  OpenMarket/OpenMarket/OpenMarketRequest/RequestConfiguration/HTTPHeaders.swift
  OpenMarket/OpenMarket/OpenMarketRequest/RequestConfiguration/URLAdditionalPath.swift
  OpenMarket/OpenMarket/OpenMarketRequest/RequestConfiguration/URLHost.swift
  OpenMarket/OpenMarket/Resources/Base.lproj/LaunchScreen.storyboard
  OpenMarket/OpenMarket/Resources/SceneDelegate.swift
  OpenMarket/OpenMarket/Scene/ProductList/Controller/ProductListViewController.swift
  OpenMarket/OpenMarket/Scene/ProductList/Model/Enum/NameSpace.swift
  OpenMarket/OpenMarket/Scene/ProductList/Model/Enum/Section.swift
  OpenMarket/OpenMarket/Scene/ProductList/View/GridCollecntionView.swift
  OpenMarket/OpenMarket/Scene/ProductList/View/GridCollectionViewCell.swift
  OpenMarket/OpenMarket/Scene/ProductList/View/ListCollectionView.swift
  OpenMarket/OpenMarket/Scene/ProductList/View/ListCollectionViewCell.swift
  OpenMarket/OpenMarket/Scene/ProductRegistration/Controller/ProductRegistrationViewController.swift
  OpenMarket/OpenMarket/Scene/ProductRegistration/View/ProductRegistrationView.swift
  OpenMarket/OpenMarket/Scene/ProductUpdate/Model/ProductUpdateView.swift
  OpenMarket/OpenMarket/Scene/ProductUpdate/Model/ProductUpdateViewController.swift
  OpenMarket/OpenMarket/TestDouble/MockSession.swift
  OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
  OpenMarket/OpenMarketTests/RequestTests.swift
Labels: style, feat, refactor

#30 Feat 19 product detail view
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/Enum/NameSpace.swift
  OpenMarket/OpenMarket/JSONModel/ProductDetail.swift
  OpenMarket/OpenMarket/JSONModel/ProductInformation.swift
  OpenMarket/OpenMarket/Scene/ProductDetail/ProductDetailViewController.swift
  OpenMarket/OpenMarket/Scene/ProductDetail/View/ImagesCollectionView.swift
  OpenMarket/OpenMarket/Scene/ProductDetail/View/ProductDetailView.swift
  OpenMarket/OpenMarket/Scene/ProductDetail/View/ProductImageCell.swift
  OpenMarket/OpenMarket/Scene/ProductList/Model/Enum/ProductList_NameSpace.swift
Labels: feat, refactor

#31 Feat 20 alert controller handler
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/OpenMarketRequest/ProductPatchRequest.swift
  OpenMarket/OpenMarket/Protocol/DataSendable.swift
  OpenMarket/OpenMarket/Scene/ProductDetail/ProductDetailViewController.swift
  OpenMarket/OpenMarket/Scene/ProductList/Controller/ProductListViewController.swift
  OpenMarket/OpenMarket/Scene/ProductList/Model/Protocol/Datable.swift
  OpenMarket/OpenMarket/Scene/ProductRegistration/View/ProductRegistrationView.swift
  OpenMarket/OpenMarket/Scene/ProductUpdate/Model/ProductUpdateView.swift
  OpenMarket/OpenMarket/Scene/ProductUpdate/Model/ProductUpdateViewController.swift
Labels: feat, refactor

#32 Refactor 8 step4
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/DataManager/OpenMarketManager.swift
  OpenMarket/OpenMarket/OpenMarketRequest/ProductGetRequest.swift
  OpenMarket/OpenMarket/OpenMarketRequest/ProductPostRequest.swift
  OpenMarket/OpenMarket/Scene/ProductDetail/ProductDetailViewController.swift
  OpenMarket/OpenMarket/Scene/ProductList/Controller/ProductListViewController.swift
  OpenMarket/OpenMarket/Scene/ProductList/Model/Enum/ProductListNameSpace.swift
  OpenMarket/OpenMarket/Scene/ProductList/View/GridCollectionViewCell.swift
  OpenMarket/OpenMarket/Scene/ProductList/View/ListCollectionViewCell.swift
  OpenMarket/OpenMarket/Scene/ProductRegistration/Controller/ProductRegistrationViewController.swift
  OpenMarket/OpenMarket/Scene/ProductRegistration/Model/ProductRegistrationManager.swift
  OpenMarket/OpenMarket/Scene/ProductRegistration/View/ProductRegistrationView.swift
  OpenMarket/OpenMarket/Scene/ProductUpdate/Model/ProductUpdateManager.swift
  OpenMarket/OpenMarket/Scene/ProductUpdate/Model/ProductUpdateView.swift
  OpenMarket/OpenMarket/Scene/ProductUpdate/Model/ProductUpdateViewController.swift
  OpenMarket/OpenMarketTests/RequestTests.swift
Labels: style, refactor, fix

#34 Step4
  OpenMarket/OpenMarket/Scene/ProductDetail/ProductDetailViewController.swift
Labels: refactor
