Repository bar-d/ios-open-market, pull requests merged in 2022-07, with the labels that each got.

#1 Feat 1 json model
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/Assets.xcassets/MockData.dataset/Contents.json
  OpenMarket/OpenMarket/Assets.xcassets/MockData.dataset/MockData.json
  OpenMarket/OpenMarket/Model/Currency.swift
  OpenMarket/OpenMarket/Model/ProductDetail.swift
  OpenMarket/OpenMarket/Model/ProductImage.swift
  OpenMarket/OpenMarket/Model/ProductsDetailList.swift
  OpenMarket/OpenMarket/Model/ProductsList.swift
  OpenMarket/OpenMarket/Model/RegisterationProduct.swift
  OpenMarket/OpenMarket/Model/SecretProducts.swift
  OpenMarket/OpenMarketTests/ParsingTests.swift
Labels: feat, test

#2 Feat 2 network
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/Error/CodableError.swift
  OpenMarket/OpenMarket/Error/NetworkError.swift
  OpenMarket/OpenMarket/Model/ProductDetail.swift
  OpenMarket/OpenMarket/Model/ProductsDetailList.swift
  OpenMarket/OpenMarket/Model/ProductsList.swift
  OpenMarket/OpenMarket/Network/APIRequest.swift
  OpenMarket/OpenMarket/TestDouble/DummyData.swift
  OpenMarket/OpenMarket/TestDouble/URLSessionProtocol.swift
  OpenMarket/OpenMarketTests/ParsingTests.swift
  OpenMarket/OpenMarketTests/RequestTests.swift
Labels: feat, refactor, test

#4 Refactor 1 step1
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/Error/CodableError.swift
  OpenMarket/OpenMarket/Error/NetworkError.swift
  OpenMarket/OpenMarket/Network/APIRequest.swift
  OpenMarket/OpenMarket/TestDouble/DummyData.swift
  OpenMarket/OpenMarket/TestDouble/MockDataRequest.swift
  OpenMarket/OpenMarket/TestDouble/MockURLSessionProtocol.swift
  OpenMarket/OpenMarket/TestDouble/URLSessionProtocol.swift
  OpenMarket/OpenMarketTests/ParsingTests.swift
  OpenMarket/OpenMarketTests/RequestTests.swift
Labels: style, refactor

#6 Feat 3 controller
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/Controller/OpenMarketViewController+extension.swift
  OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
  OpenMarket/OpenMarket/Controller/ViewController.swift
  OpenMarket/OpenMarket/Model/Network/MyURLSession.swift
  OpenMarket/OpenMarket/Resources/AppDelegate.swift
  OpenMarket/OpenMarket/Resources/Info.plist
  OpenMarket/OpenMarket/Resources/SceneDelegate.swift
  OpenMarket/OpenMarket/TestDouble/MockSession.swift
  OpenMarket/OpenMarket/View/Base.lproj/Main.storyboard
  OpenMarket/OpenMarketTests/ParsingTests.swift
  OpenMarket/OpenMarketTests/RequestTests.swift
Labels: feat, refactor

#7 feat: ListCollectionView 구현
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
  OpenMarket/OpenMarket/Model/JSONModel/ProductDetail.swift
Labels: feat

#8 Feat 6 grid collection view
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
  OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
Labels: feat

#9 feat: 로딩 뷰 구현
  OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
Labels: feat

#11 refactor: 불필요한 구문 제거
  OpenMarket/OpenMarket/Controller/OpenMarketViewController+extension.swift
Labels: refactor

#12 refactor: 함수 순서 변경
  OpenMarket/OpenMarket/Controller/OpenMarketViewController+extension.swift
Labels: refactor

#13 Refactor 2 step2
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
  OpenMarket/OpenMarket/Model/Data/ProductsRequest.swift
  OpenMarket/OpenMarket/Model/Extension/NSMutableAttributedString+extension.swift
  OpenMarket/OpenMarket/Model/Extension/ProductDetail+extension.swift
  OpenMarket/OpenMarket/Model/JSONModel/ProductDetail.swift
  OpenMarket/OpenMarket/Model/Network/APIRequest.swift
  OpenMarket/OpenMarket/View/GridCollecntionView.swift
  OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
  OpenMarket/OpenMarket/View/ListCollectionView.swift
Labels: style, refactor

#14 feat: refresh controll 구현
  OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
  OpenMarket/OpenMarket/View/GridCollecntionView.swift
  OpenMarket/OpenMarket/View/ListCollectionView.swift
Labels: feat

#15 Refactor 3 step2review
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/Controller/OpenMarketViewController+extension.swift
  OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
  OpenMarket/OpenMarket/Model/Data/ImageCacheManager.swift
  OpenMarket/OpenMarket/Model/Data/OpenMarketRequest.swift
  OpenMarket/OpenMarket/Model/Data/ProductsRequest.swift
  OpenMarket/OpenMarket/Model/Enum/Section.swift
  OpenMarket/OpenMarket/Model/JSONModel/ProductDetail.swift
  OpenMarket/OpenMarket/Model/Network/APIRequest.swift
  OpenMarket/OpenMarket/Model/Network/MyURLSession.swift
  OpenMarket/OpenMarket/Model/Network/SessionProtocol.swift
  OpenMarket/OpenMarket/TestDouble/MockSession.swift
  OpenMarket/OpenMarket/View/GridCollecntionView.swift
  OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
  OpenMarket/OpenMarket/View/ListCollectionView.swift
  OpenMarket/OpenMarketTests/RequestTests.swift
Labels: refactor, fix

#17 Feat 10 UI image picker controller
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/Controller/OpenMarketViewController.swift
  OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
  OpenMarket/OpenMarket/Model/Extension/UIView+extension.swift
  OpenMarket/OpenMarket/Resources/Info.plist
  OpenMarket/OpenMarket/View/GridCollectionViewCell.swift
  OpenMarket/OpenMarket/View/ListCollectionView.swift
  OpenMarket/OpenMarket/View/ListCollectionViewCell.swift
  OpenMarket/OpenMarket/View/ProductRegistrationView.swift
  OpenMarket/OpenMarketTests/RequestTests.swift
Labels: feat, refactor, fix

#18 Feat 11 navigation controller
  OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
  OpenMarket/OpenMarket/View/ProductRegistrationView.swift
Labels: feat

#19 feat: postProduct 구현
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/Controller/ProductRegistrationViewController.swift
  OpenMarket/OpenMarket/Model/Enum/Currency.swift
  OpenMarket/OpenMarket/View/ProductRegistrationView.swift
Labels: feat

#20 Feat 13 keyboard
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/Model/Extension/Int+extension.swift
  OpenMarket/OpenMarket/Model/JSONModel/ProductDetail.swift
  OpenMarket/OpenMarket/View/ProductRegistrationView.swift
Labels: style, refactor, fix

#23 Feat 16 product input limit
  OpenMarket/OpenMarket/Model/Protocol/Requestable.swift
  OpenMarket/OpenMarket/View/ProductRegistrationView.swift
Labels: feat

#24 refactor: data 타입의 append 함수 추가
  OpenMarket/OpenMarket.xcodeproj/project.pbxproj
  OpenMarket/OpenMarket/Model/Extension/Data+extension.swift
  OpenMarket/OpenMarket/Model/Extension/Double+extension.swift
  OpenMarket/OpenMarket/Model/Network/APIRequest.swift
Labels: refactor
